// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGTdWstqbR6wn-Y81PdRcsnFvPYH5nso',
    appId: '1:700901312627:web:c2dfd9dcd0d03865050206',
    messagingSenderId: '700901312627',
    projectId: 'mubs-locator',
    authDomain: 'mubs-locator.firebaseapp.com',
    storageBucket: 'mubs-locator.firebasestorage.app',
    measurementId: 'G-8P9GNWXC5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTqbZ0H-uvPmELnETwgfKhyhbHs-GghKk',
    appId: '1:700901312627:android:cc7bd9e19054378c050206',
    messagingSenderId: '700901312627',
    projectId: 'mubs-locator',
    storageBucket: 'mubs-locator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VQoy0UNEW3_7lCIJYBATpd7EJ-hqJxg',
    appId: '1:700901312627:ios:3faa66d8523ab0e3050206',
    messagingSenderId: '700901312627',
    projectId: 'mubs-locator',
    storageBucket: 'mubs-locator.firebasestorage.app',
    iosBundleId: 'com.example.mubsLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VQoy0UNEW3_7lCIJYBATpd7EJ-hqJxg',
    appId: '1:700901312627:ios:3faa66d8523ab0e3050206',
    messagingSenderId: '700901312627',
    projectId: 'mubs-locator',
    storageBucket: 'mubs-locator.firebasestorage.app',
    iosBundleId: 'com.example.mubsLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKGTdWstqbR6wn-Y81PdRcsnFvPYH5nso',
    appId: '1:700901312627:web:193e801993b8ea5e050206',
    messagingSenderId: '700901312627',
    projectId: 'mubs-locator',
    authDomain: 'mubs-locator.firebaseapp.com',
    storageBucket: 'mubs-locator.firebasestorage.app',
    measurementId: 'G-DZFNFXKKN9',
  );
}
