platform :ios, '15.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Manual pod declarations for all Flutter plugins
  pod 'GoogleMaps', '~> 9.1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'flutter_local_notifications'
  pod 'permission_handler'
  pod 'google_sign_in'
  pod 'image_picker'
  pod 'share_plus'
  pod 'url_launcher'
  pod 'shared_preferences'
  pod 'geolocator'
  pod 'flutter_polyline_points'
  pod 'intl'
  pod 'cloud_functions'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fix for M1/M2 simulator builds
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
