name: Flutter iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Flutter (MATCH YOUR LOCAL VERSION)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          channel: 'stable'

      # 3️⃣ Verify Flutter version
      - name: Verify Flutter version
        run: flutter --version

      # 4️⃣ Pre-cache iOS Flutter artifacts
      - name: Precache Flutter iOS
        run: flutter precache --ios

      # 5️⃣ Install Signing Certificate
      - name: Install signing certificate
        env:
          CERT_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          CERT_BASE64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
        run: |
          echo "$CERT_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          security import certificate.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "$CERT_PASSWORD" \
            -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain

      # 6️⃣ Install Provisioning Profile
      - name: Install provisioning profile
        env:
          PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      # 7️⃣ Flutter Build (No Code Sign)
      - name: Build Flutter iOS
        run: flutter build ios --release --no-codesign

      # 8️⃣ Archive with Xcode
      - name: Archive iOS app
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
          PROFILE_NAME: ${{ secrets.APPLE_PROVISIONING_PROFILE_NAME }}
        run: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/Runner.xcarchive archive \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$APPLE_BUNDLE_ID \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"

      # 9️⃣ Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $PWD/build

      # 🔟 Upload IPA as Build Artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/*.ipa
